import '@/styles/globals.scss'

import { Courier_Prime } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import Navbar from '@/components/navbar'

const courier = Courier_Prime({ 
  weight: ["400", "700"],
  subsets: ['latin'] 
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>

    <html lang="en">
      <body className={courier.className}>
        <Navbar />
        { children }
      </body>
    </html>

    </ClerkProvider>
  )
}
